{
 "title": "Smart Home",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "Tarif base", "query": "0.0002276" },
   { "name": "bleu_hc", "label": "Bleu HC", "query": "0.0001056" },
   { "name": "bleu_hp", "label": "Bleu HP", "query": "0.0001369" },
   { "name": "blanc_hc", "label": "Blanc HC", "query": "0.0001246" },
   { "name": "blanc_hp", "label": "Blanc HP", "query": "0.0001654" },
   { "name": "rouge_hc", "label": "Rouge HC", "query": "0.0001328" },
   { "name": "rouge_hp", "label": "Rouge HP", "query": "0.0007324" },
   { "name": "hc", "label": "HC", "query": "0.0001828" },
   { "name": "hp", "label": "HP", "query": "0.0002460" },
   {
    "name": "unique_id_bleu_hp",
    "query": "00:15:8d:00:09:66:cc:41-01-0702"
   },
   {
    "name": "unique_id_bleu_hc",
    "query": "00:15:8d:00:09:66:cc:41-02-0702"
   },
   {
    "name": "unique_id_blanc_hp",
    "query": "00:15:8d:00:09:66:cc:41-03-0702"
   },
   {
    "name": "unique_id_blanc_hc",
    "query": "00:15:8d:00:09:66:cc:41-04-0702"
   },
   {
    "name": "unique_id_rouge_hp",
    "query": "00:15:8d:00:09:66:cc:41-05-0702"
   },
   {
    "name": "unique_id_rouge_hc",
    "query": "00:15:8d:00:09:66:cc:41-06-0702"
   }
  ]
 },
 "panels": [
  { "title": "Capteurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie des capteurs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pression",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Linky", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Répartition",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "$tag_uniqueid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "uniqueid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Tempo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "alias": "HP Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " * $bleu_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "HC Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $bleu_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "HP Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $blanc_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "HC Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $blanc_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "HP Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $rouge_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "HC Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $rouge_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Détail Tempo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "alias": "HP Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " * $bleu_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "HC Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $bleu_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "HP Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $blanc_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "HC Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $blanc_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "HP Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $rouge_hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "HC Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $rouge_hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Tarif Base",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "alias": "HP Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " * $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "HC Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "HP Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "HC Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "HP Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "HC Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $base" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "alias": "HP Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "HC Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "HP Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "HC Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "HP Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "HC Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Total HCHP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "alias": "HP Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " * $hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "HC Bleu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "HP Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "HC Blanc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "HP Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $hp" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "HC Rouge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "consumption",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* $hc" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Consommation électrique",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hp$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_bleu_hc$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hp$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_blanc_hc$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hp$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT difference(mean(\"consumption\")) FROM \"consumption\" WHERE $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "uniqueid", "operator": "=~", "value": "/^$unique_id_rouge_hc$/" }
     ]
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}